name: publish

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
#    needs: publish-dev-image
    runs-on: ubuntu-latest

    steps:
      - name: Create SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ../private.key
          sudo chmod 600 ../private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.DEV_SSH_PRIVATE}}
          SSH_KNOWN_HOSTS: ${{secrets.DEV_SSH_KNOWN_HOSTS}}

      - name: Connect via SSH and deploy
        run: |
          ssh -i $SSH_KEY_PATH facundobocalandro@${{secrets.DEV_SSH_HOST}}
          sudo ~/deploy-service client
        shell: bash
        env:
          SSH_KEY_PATH: ${{ github.workspace }}/../private.key
